export default {
  products:[
    {
      _id: '1',
      name: 'Frock',
      category: 'less than 6 yrs',
      image: '/images/black.jpeg',
      price: 1000,
      brand: 'Hers',
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: '2',
      name: 'Frock',
      category: '6 to 9 yrs',
      image: '/images/red.jpeg',
      price: 1000,
      brand: 'Hers',
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: '3',
      name: 'Frock',
      category: '10 to 13 yrs',
      image: '/images/purple.jpeg',
      price: 1000,
      brand: 'Hers',
      rating: 4.5,
      numReviews: 10,
      countInStock: 4,
    },
    {
      _id: '4',
      name: 'Frock',
      category: '14 to 17 yrs',
      image: '/images/green.jpeg',
      price: 1000,
      brand: 'Hers',
      rating: 4.5,
      numReviews: 10,
      countInStock: 3,
    },
    {
      _id: '5',
      name: 'Frock',
      category: '18 yrs and above',
      image: '/images/maroon.jpeg',
      price: 1000,
      brand: 'Hers',
      rating: 4.5,
      numReviews: 10,
      countInStock: 2,
    },
    {
      _id: '6',
      name: 'Frock',
      category: 'Wedding Gowns',
      image: '/images/blue.jpeg',
      price: 1000,
      brand: 'Hers',
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
    },
  ]
}
